2023-08-03 22:01:08,513 INFO    StreamThr :1453 [internal.py:wandb_internal():86] W&B internal server running at pid: 1453, started at: 2023-08-03 22:01:08.513217
2023-08-03 22:01:08,517 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: status
2023-08-03 22:01:08,520 INFO    WriterThread:1453 [datastore.py:open_for_write():85] open: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/run-59l06gmp.wandb
2023-08-03 22:01:08,520 DEBUG   SenderThread:1453 [sender.py:send():375] send: header
2023-08-03 22:01:08,617 DEBUG   SenderThread:1453 [sender.py:send():375] send: run
2023-08-03 22:01:09,498 INFO    SenderThread:1453 [dir_watcher.py:__init__():219] watching files in: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files
2023-08-03 22:01:09,499 INFO    SenderThread:1453 [sender.py:_start_run_threads():1124] run started: 59l06gmp with start time 1691071268.514389
2023-08-03 22:01:09,499 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: summary_record
2023-08-03 22:01:09,499 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: check_version
2023-08-03 22:01:09,499 INFO    SenderThread:1453 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-08-03 22:01:09,500 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: check_version
2023-08-03 22:01:09,866 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: run_start
2023-08-03 22:01:09,875 DEBUG   HandlerThread:1453 [system_info.py:__init__():31] System info init
2023-08-03 22:01:09,875 DEBUG   HandlerThread:1453 [system_info.py:__init__():46] System info init done
2023-08-03 22:01:09,875 INFO    HandlerThread:1453 [system_monitor.py:start():181] Starting system monitor
2023-08-03 22:01:09,875 INFO    SystemMonitor:1453 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-08-03 22:01:09,875 INFO    HandlerThread:1453 [system_monitor.py:probe():201] Collecting system info
2023-08-03 22:01:09,876 INFO    SystemMonitor:1453 [interfaces.py:start():190] Started cpu monitoring
2023-08-03 22:01:09,877 INFO    SystemMonitor:1453 [interfaces.py:start():190] Started disk monitoring
2023-08-03 22:01:09,877 INFO    SystemMonitor:1453 [interfaces.py:start():190] Started gpu monitoring
2023-08-03 22:01:09,878 INFO    SystemMonitor:1453 [interfaces.py:start():190] Started memory monitoring
2023-08-03 22:01:09,880 INFO    SystemMonitor:1453 [interfaces.py:start():190] Started network monitoring
2023-08-03 22:01:09,889 DEBUG   HandlerThread:1453 [system_info.py:probe():195] Probing system
2023-08-03 22:01:09,896 DEBUG   HandlerThread:1453 [system_info.py:_probe_git():180] Probing git
2023-08-03 22:01:09,907 DEBUG   HandlerThread:1453 [system_info.py:_probe_git():188] Probing git done
2023-08-03 22:01:09,907 DEBUG   HandlerThread:1453 [system_info.py:probe():240] Probing system done
2023-08-03 22:01:09,908 DEBUG   HandlerThread:1453 [system_monitor.py:probe():210] {'os': 'Linux-5.4.0-99-generic-x86_64-with-glibc2.17', 'python': '3.8.10', 'heartbeatAt': '2023-08-03T14:01:09.890047', 'startedAt': '2023-08-03T14:01:08.505436', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/root/autodl-tmp/llama_ppo.py', 'git': {'remote': 'https://github.com/ZihangZ/msc_project.git', 'commit': '0fa2196e950e6264b0a151d4d41f1cf70bac9dcc'}, 'email': 'ryanzengzh@gmail.com', 'root': '/root/autodl-tmp/msc_project', 'host': 'autodl-container-cada1195fa-f628a5d3', 'username': 'root', 'executable': '/root/miniconda3/bin/python', 'cpu_count': 40, 'cpu_count_logical': 80, 'cpu_freq': {'current': 2999.848999999995, 'min': 0.0, 'max': 0.0}, 'cpu_freq_per_core': [{'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}, {'current': 2999.849, 'min': 0.0, 'max': 0.0}], 'disk': {'total': 30.0, 'used': 8.607795715332031}, 'gpu': 'Tesla V100S-PCIE-32GB', 'gpu_count': 1, 'gpu_devices': [{'name': 'Tesla V100S-PCIE-32GB', 'memory_total': 34359738368}], 'memory': {'total': 629.8885612487793}}
2023-08-03 22:01:09,908 INFO    HandlerThread:1453 [system_monitor.py:probe():211] Finished collecting system info
2023-08-03 22:01:09,908 INFO    HandlerThread:1453 [system_monitor.py:probe():214] Publishing system info
2023-08-03 22:01:09,908 DEBUG   HandlerThread:1453 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-08-03 22:01:09,908 DEBUG   HandlerThread:1453 [system_info.py:_save_pip():67] Saving pip packages done
2023-08-03 22:01:09,908 DEBUG   HandlerThread:1453 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-08-03 22:01:10,366 DEBUG   HandlerThread:1453 [system_info.py:_save_conda():86] Saving conda packages done
2023-08-03 22:01:10,367 INFO    HandlerThread:1453 [system_monitor.py:probe():216] Finished publishing system info
2023-08-03 22:01:10,374 DEBUG   SenderThread:1453 [sender.py:send():375] send: files
2023-08-03 22:01:10,374 INFO    SenderThread:1453 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2023-08-03 22:01:10,380 DEBUG   SenderThread:1453 [sender.py:send():375] send: telemetry
2023-08-03 22:01:10,382 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: stop_status
2023-08-03 22:01:10,382 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: stop_status
2023-08-03 22:01:10,500 INFO    Thread-12 :1453 [dir_watcher.py:_on_file_created():278] file/dir created: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/wandb-metadata.json
2023-08-03 22:01:10,500 INFO    Thread-12 :1453 [dir_watcher.py:_on_file_created():278] file/dir created: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/requirements.txt
2023-08-03 22:01:10,500 INFO    Thread-12 :1453 [dir_watcher.py:_on_file_created():278] file/dir created: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/wandb-summary.json
2023-08-03 22:01:10,500 INFO    Thread-12 :1453 [dir_watcher.py:_on_file_created():278] file/dir created: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/conda-environment.yaml
2023-08-03 22:01:10,929 DEBUG   SenderThread:1453 [sender.py:send():375] send: config
2023-08-03 22:01:10,963 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-metadata.json?Expires=1691157670&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XWOeT%2BxequiG15fpNbUVz0BXnSnwMf1%2F01RgRLCpVsYhchivkXffpasQ%2B7TyUJIFvU9jHDPs70Nth23guB9iySim5BUpbIrzJWYr7sj83Z9Q5WB8ua%2BfGjj9iUvb0rTkH7mrF90wf%2Fm%2FLIey8fRtY4EsvN5QdjcDq0AEupkWNvJXsz5rLp3%2BtilYrI9G%2FqOXdNXFVss4jWpEQdGc5eq1jR6%2FDJIl84hTYXrLKAb25229M%2BK%2BMmXLGHNQXBqwmUdarEjD4N6%2BH8ataDF10PI%2FMmbbCKiEnOGFAVL00z%2B9654GnL%2BiC8IblD5jXIxWRQRZogqf2W%2BgbSPu2XDkRJMmKw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:10,963 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9248'}
2023-08-03 22:01:10,963 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:11,501 INFO    Thread-12 :1453 [dir_watcher.py:_on_file_created():278] file/dir created: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/output.log
2023-08-03 22:01:12,331 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-metadata.json?Expires=1691157670&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XWOeT%2BxequiG15fpNbUVz0BXnSnwMf1%2F01RgRLCpVsYhchivkXffpasQ%2B7TyUJIFvU9jHDPs70Nth23guB9iySim5BUpbIrzJWYr7sj83Z9Q5WB8ua%2BfGjj9iUvb0rTkH7mrF90wf%2Fm%2FLIey8fRtY4EsvN5QdjcDq0AEupkWNvJXsz5rLp3%2BtilYrI9G%2FqOXdNXFVss4jWpEQdGc5eq1jR6%2FDJIl84hTYXrLKAb25229M%2BK%2BMmXLGHNQXBqwmUdarEjD4N6%2BH8ataDF10PI%2FMmbbCKiEnOGFAVL00z%2B9654GnL%2BiC8IblD5jXIxWRQRZogqf2W%2BgbSPu2XDkRJMmKw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:12,331 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9248'}
2023-08-03 22:01:12,331 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:13,501 INFO    Thread-12 :1453 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/output.log
2023-08-03 22:01:13,807 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: status_report
2023-08-03 22:01:15,091 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-metadata.json?Expires=1691157670&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XWOeT%2BxequiG15fpNbUVz0BXnSnwMf1%2F01RgRLCpVsYhchivkXffpasQ%2B7TyUJIFvU9jHDPs70Nth23guB9iySim5BUpbIrzJWYr7sj83Z9Q5WB8ua%2BfGjj9iUvb0rTkH7mrF90wf%2Fm%2FLIey8fRtY4EsvN5QdjcDq0AEupkWNvJXsz5rLp3%2BtilYrI9G%2FqOXdNXFVss4jWpEQdGc5eq1jR6%2FDJIl84hTYXrLKAb25229M%2BK%2BMmXLGHNQXBqwmUdarEjD4N6%2BH8ataDF10PI%2FMmbbCKiEnOGFAVL00z%2B9654GnL%2BiC8IblD5jXIxWRQRZogqf2W%2BgbSPu2XDkRJMmKw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:15,091 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9248'}
2023-08-03 22:01:15,092 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:15,092 INFO    wandb-upload_0:1453 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2123, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-08-03 22:01:15,502 INFO    Thread-12 :1453 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/output.log
2023-08-03 22:01:17,502 INFO    Thread-12 :1453 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/output.log
2023-08-03 22:01:19,022 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: status_report
2023-08-03 22:01:19,503 INFO    Thread-12 :1453 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/output.log
2023-08-03 22:01:19,528 DEBUG   SenderThread:1453 [sender.py:send():375] send: exit
2023-08-03 22:01:19,528 INFO    SenderThread:1453 [sender.py:send_exit():598] handling exit code: 1
2023-08-03 22:01:19,528 INFO    SenderThread:1453 [sender.py:send_exit():600] handling runtime: 9
2023-08-03 22:01:19,529 INFO    SenderThread:1453 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-08-03 22:01:19,529 INFO    SenderThread:1453 [sender.py:send_exit():606] send defer
2023-08-03 22:01:19,530 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: defer
2023-08-03 22:01:19,530 INFO    HandlerThread:1453 [handler.py:handle_request_defer():170] handle defer: 0
2023-08-03 22:01:19,530 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: defer
2023-08-03 22:01:19,530 INFO    SenderThread:1453 [sender.py:send_request_defer():622] handle sender defer: 0
2023-08-03 22:01:19,530 INFO    SenderThread:1453 [sender.py:transition_state():626] send defer: 1
2023-08-03 22:01:19,530 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: defer
2023-08-03 22:01:19,530 INFO    HandlerThread:1453 [handler.py:handle_request_defer():170] handle defer: 1
2023-08-03 22:01:19,531 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: defer
2023-08-03 22:01:19,531 INFO    SenderThread:1453 [sender.py:send_request_defer():622] handle sender defer: 1
2023-08-03 22:01:19,531 INFO    SenderThread:1453 [sender.py:transition_state():626] send defer: 2
2023-08-03 22:01:19,531 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: defer
2023-08-03 22:01:19,531 INFO    HandlerThread:1453 [handler.py:handle_request_defer():170] handle defer: 2
2023-08-03 22:01:19,531 INFO    HandlerThread:1453 [system_monitor.py:finish():190] Stopping system monitor
2023-08-03 22:01:19,531 DEBUG   SystemMonitor:1453 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-08-03 22:01:19,531 DEBUG   SystemMonitor:1453 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-08-03 22:01:19,531 DEBUG   SystemMonitor:1453 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-08-03 22:01:19,532 INFO    HandlerThread:1453 [interfaces.py:finish():202] Joined cpu monitor
2023-08-03 22:01:19,532 INFO    HandlerThread:1453 [interfaces.py:finish():202] Joined disk monitor
2023-08-03 22:01:19,540 INFO    HandlerThread:1453 [interfaces.py:finish():202] Joined gpu monitor
2023-08-03 22:01:19,540 INFO    HandlerThread:1453 [interfaces.py:finish():202] Joined memory monitor
2023-08-03 22:01:19,540 INFO    HandlerThread:1453 [interfaces.py:finish():202] Joined network monitor
2023-08-03 22:01:19,541 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: defer
2023-08-03 22:01:19,541 INFO    SenderThread:1453 [sender.py:send_request_defer():622] handle sender defer: 2
2023-08-03 22:01:19,541 INFO    SenderThread:1453 [sender.py:transition_state():626] send defer: 3
2023-08-03 22:01:19,541 DEBUG   SenderThread:1453 [sender.py:send():375] send: stats
2023-08-03 22:01:19,541 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: defer
2023-08-03 22:01:19,541 INFO    HandlerThread:1453 [handler.py:handle_request_defer():170] handle defer: 3
2023-08-03 22:01:19,541 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: defer
2023-08-03 22:01:19,541 INFO    SenderThread:1453 [sender.py:send_request_defer():622] handle sender defer: 3
2023-08-03 22:01:19,541 INFO    SenderThread:1453 [sender.py:transition_state():626] send defer: 4
2023-08-03 22:01:19,542 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: defer
2023-08-03 22:01:19,542 INFO    HandlerThread:1453 [handler.py:handle_request_defer():170] handle defer: 4
2023-08-03 22:01:19,542 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: defer
2023-08-03 22:01:19,542 INFO    SenderThread:1453 [sender.py:send_request_defer():622] handle sender defer: 4
2023-08-03 22:01:19,542 INFO    SenderThread:1453 [sender.py:transition_state():626] send defer: 5
2023-08-03 22:01:19,542 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: defer
2023-08-03 22:01:19,542 INFO    HandlerThread:1453 [handler.py:handle_request_defer():170] handle defer: 5
2023-08-03 22:01:19,542 DEBUG   SenderThread:1453 [sender.py:send():375] send: summary
2023-08-03 22:01:19,543 INFO    SenderThread:1453 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-08-03 22:01:19,543 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: defer
2023-08-03 22:01:19,543 INFO    SenderThread:1453 [sender.py:send_request_defer():622] handle sender defer: 5
2023-08-03 22:01:19,543 INFO    SenderThread:1453 [sender.py:transition_state():626] send defer: 6
2023-08-03 22:01:19,543 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: defer
2023-08-03 22:01:19,543 INFO    HandlerThread:1453 [handler.py:handle_request_defer():170] handle defer: 6
2023-08-03 22:01:19,544 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: defer
2023-08-03 22:01:19,544 INFO    SenderThread:1453 [sender.py:send_request_defer():622] handle sender defer: 6
2023-08-03 22:01:19,547 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: status_report
2023-08-03 22:01:19,909 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-metadata.json?Expires=1691157670&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XWOeT%2BxequiG15fpNbUVz0BXnSnwMf1%2F01RgRLCpVsYhchivkXffpasQ%2B7TyUJIFvU9jHDPs70Nth23guB9iySim5BUpbIrzJWYr7sj83Z9Q5WB8ua%2BfGjj9iUvb0rTkH7mrF90wf%2Fm%2FLIey8fRtY4EsvN5QdjcDq0AEupkWNvJXsz5rLp3%2BtilYrI9G%2FqOXdNXFVss4jWpEQdGc5eq1jR6%2FDJIl84hTYXrLKAb25229M%2BK%2BMmXLGHNQXBqwmUdarEjD4N6%2BH8ataDF10PI%2FMmbbCKiEnOGFAVL00z%2B9654GnL%2BiC8IblD5jXIxWRQRZogqf2W%2BgbSPu2XDkRJMmKw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:19,910 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9248'}
2023-08-03 22:01:19,910 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:19,940 INFO    SenderThread:1453 [sender.py:transition_state():626] send defer: 7
2023-08-03 22:01:19,940 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: defer
2023-08-03 22:01:19,940 INFO    HandlerThread:1453 [handler.py:handle_request_defer():170] handle defer: 7
2023-08-03 22:01:19,940 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: defer
2023-08-03 22:01:19,940 INFO    SenderThread:1453 [sender.py:send_request_defer():622] handle sender defer: 7
2023-08-03 22:01:20,503 INFO    Thread-12 :1453 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/config.yaml
2023-08-03 22:01:20,504 INFO    Thread-12 :1453 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/wandb-summary.json
2023-08-03 22:01:20,528 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:20,956 INFO    SenderThread:1453 [sender.py:transition_state():626] send defer: 8
2023-08-03 22:01:20,956 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:20,956 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: defer
2023-08-03 22:01:20,957 INFO    HandlerThread:1453 [handler.py:handle_request_defer():170] handle defer: 8
2023-08-03 22:01:20,959 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: defer
2023-08-03 22:01:20,959 INFO    SenderThread:1453 [sender.py:send_request_defer():622] handle sender defer: 8
2023-08-03 22:01:20,959 INFO    SenderThread:1453 [sender.py:transition_state():626] send defer: 9
2023-08-03 22:01:20,960 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: defer
2023-08-03 22:01:20,960 INFO    HandlerThread:1453 [handler.py:handle_request_defer():170] handle defer: 9
2023-08-03 22:01:20,960 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: defer
2023-08-03 22:01:20,960 INFO    SenderThread:1453 [sender.py:send_request_defer():622] handle sender defer: 9
2023-08-03 22:01:20,960 INFO    SenderThread:1453 [dir_watcher.py:finish():365] shutting down directory watcher
2023-08-03 22:01:21,504 INFO    Thread-12 :1453 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/output.log
2023-08-03 22:01:21,504 INFO    SenderThread:1453 [dir_watcher.py:finish():395] scan: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files
2023-08-03 22:01:21,504 INFO    SenderThread:1453 [dir_watcher.py:finish():409] scan save: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/config.yaml config.yaml
2023-08-03 22:01:21,505 INFO    SenderThread:1453 [dir_watcher.py:finish():409] scan save: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/wandb-summary.json wandb-summary.json
2023-08-03 22:01:21,505 INFO    SenderThread:1453 [dir_watcher.py:finish():409] scan save: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/requirements.txt requirements.txt
2023-08-03 22:01:21,505 INFO    SenderThread:1453 [dir_watcher.py:finish():409] scan save: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/conda-environment.yaml conda-environment.yaml
2023-08-03 22:01:21,505 INFO    SenderThread:1453 [dir_watcher.py:finish():409] scan save: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/wandb-metadata.json wandb-metadata.json
2023-08-03 22:01:21,505 INFO    SenderThread:1453 [dir_watcher.py:finish():409] scan save: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/output.log output.log
2023-08-03 22:01:21,506 INFO    SenderThread:1453 [sender.py:transition_state():626] send defer: 10
2023-08-03 22:01:21,509 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: defer
2023-08-03 22:01:21,509 INFO    HandlerThread:1453 [handler.py:handle_request_defer():170] handle defer: 10
2023-08-03 22:01:21,512 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: defer
2023-08-03 22:01:21,512 INFO    SenderThread:1453 [sender.py:send_request_defer():622] handle sender defer: 10
2023-08-03 22:01:21,512 INFO    SenderThread:1453 [file_pusher.py:finish():168] shutting down file pusher
2023-08-03 22:01:21,529 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:21,529 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:22,341 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/output.log?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftpQ%2FuUigniI%2F9XD1AMUUMOqpkJ6JLZ4O20G0JRF%2FOwA5IfJzZCyO4%2Fin00RwETvx7aRVgBAs4fSOahG3BK8YZx0G9CkGK3Ta08WjNow1YW%2B1MTJNV5nuV1Chin2yW6H2bRnbLJezUOSR2FpsoIxFXdyjnlF3wYIimFYkOwVQ18KgCQiThtGHV1BFYhbEF2TxZ834nnxA0w6sWP11Ffqz8odGycAWJOnfxCehvqe08JwzLBzs3U%2BQ9ZWIIg6dDR3Ontt7XE2Ezy3Oe4bGsVcnKAT9EQKTHe4aDiVrSnGqquHqQFdM2vIlMpfFFheEh5NYidy%2BRPu23nctMIgaQWd5g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:22,341 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6417'}
2023-08-03 22:01:22,341 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:22,387 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-summary.json?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RI1vMhDYjBNPlY9n58%2BQCMWxXUl0IK8RVtsFsbV3MzTqNiqJZxLblFVkyF92P%2FQe%2BzxgifQsflI66FkOH3Oj78jNES8TV3deCn5tS9VqC4QILwHGCPlLWa%2FrY6N6gyejOt21OdMN8976kzjCSbwIV6H1dus%2FWzYBfEk4m7rvmmMDyW2hfDR59HVDXWybfHkU2Z6psXocnPnoTBp5PsaW32jw4d1I%2BeX0UEZTv9maFX6WRXotLzve1fsaQcIlo9coNgbp%2FTUWhc9pypZI%2F1%2FyXMzTs8adoC9JnwME0q%2BD%2F7LVopEWT57C98RfZRh%2Flaa0bvh9j5pIbe5UDrYT52uoqg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:22,387 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-08-03 22:01:22,387 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:22,530 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:22,530 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:22,593 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/requirements.txt?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HIDwxPOA%2Bs9BJuS%2B644bpHIAjHghLwRoRhadGyo5qMgJRh4WiNzpKk7lX3gdhT6oIhncH%2FfcOPoMhjLJF00rdeSmFnSdaiNYi1ZnTeiHwIcsH%2Bd2uptiNOn%2FZ0oOaxWCaf6uK3SihsXZN%2FYHtxhyFhzpnJg7u0K6xtJYBl19T1Yzay%2FP6Tg%2FJz%2FKD9Q0wqnFMsF%2FR%2FceFU5vPOcKQpgx8LofJK6Jophgj8FlEjFsxJ6dc6jd%2F2bTXdexC1bIFCI3eyiz%2FzLDY73zDRTqqqczFCRMJOOdyI%2FkBfO8l4131ocTGo%2F45Q1M2NAA5EmBQ8L68og3ERdY%2BuFfHEptrueqYQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:22,593 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4263'}
2023-08-03 22:01:22,593 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:22,596 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/config.yaml?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZwCS2fhe%2BxdM23zT84rm8uJMfSS1EBGIe1uWzSj46Va5MuJLh%2BdrCULvHUggHy7QEYFCkLXWtAxIBnFaEccqXDdNpbegIKiLDDqAfNIPW2UuYbQwa15qTxuhII5G1VMz%2F3xllNetvUtkOmSq8JhfDE%2BUXPPaGpVaTn8zPXHFvKN1RAAefNnRoSLWy7%2FV1Uaob5MfPYX%2FjQgy4DO1D6GwqrGxqO%2B7aMyhQlCsKO6NUJfITJOt1wAkbTlG%2FPRgSbbEaG4uK8tgZZsJDnyCboXPOBC5ARaIxkaL2pRdKp0bu4urMkqr9t89AI4gj%2BVsbGKXWBbpGhiR%2FkLS3civssHB%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:22,597 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1206'}
2023-08-03 22:01:22,597 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:23,518 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/output.log?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftpQ%2FuUigniI%2F9XD1AMUUMOqpkJ6JLZ4O20G0JRF%2FOwA5IfJzZCyO4%2Fin00RwETvx7aRVgBAs4fSOahG3BK8YZx0G9CkGK3Ta08WjNow1YW%2B1MTJNV5nuV1Chin2yW6H2bRnbLJezUOSR2FpsoIxFXdyjnlF3wYIimFYkOwVQ18KgCQiThtGHV1BFYhbEF2TxZ834nnxA0w6sWP11Ffqz8odGycAWJOnfxCehvqe08JwzLBzs3U%2BQ9ZWIIg6dDR3Ontt7XE2Ezy3Oe4bGsVcnKAT9EQKTHe4aDiVrSnGqquHqQFdM2vIlMpfFFheEh5NYidy%2BRPu23nctMIgaQWd5g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:23,519 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6417'}
2023-08-03 22:01:23,519 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:23,519 INFO    wandb-upload_4:1453 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2123, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-08-03 22:01:23,530 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:23,531 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:23,581 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-summary.json?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RI1vMhDYjBNPlY9n58%2BQCMWxXUl0IK8RVtsFsbV3MzTqNiqJZxLblFVkyF92P%2FQe%2BzxgifQsflI66FkOH3Oj78jNES8TV3deCn5tS9VqC4QILwHGCPlLWa%2FrY6N6gyejOt21OdMN8976kzjCSbwIV6H1dus%2FWzYBfEk4m7rvmmMDyW2hfDR59HVDXWybfHkU2Z6psXocnPnoTBp5PsaW32jw4d1I%2BeX0UEZTv9maFX6WRXotLzve1fsaQcIlo9coNgbp%2FTUWhc9pypZI%2F1%2FyXMzTs8adoC9JnwME0q%2BD%2F7LVopEWT57C98RfZRh%2Flaa0bvh9j5pIbe5UDrYT52uoqg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:23,582 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-08-03 22:01:23,582 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:23,582 INFO    wandb-upload_2:1453 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2123, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-08-03 22:01:23,763 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/requirements.txt?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HIDwxPOA%2Bs9BJuS%2B644bpHIAjHghLwRoRhadGyo5qMgJRh4WiNzpKk7lX3gdhT6oIhncH%2FfcOPoMhjLJF00rdeSmFnSdaiNYi1ZnTeiHwIcsH%2Bd2uptiNOn%2FZ0oOaxWCaf6uK3SihsXZN%2FYHtxhyFhzpnJg7u0K6xtJYBl19T1Yzay%2FP6Tg%2FJz%2FKD9Q0wqnFMsF%2FR%2FceFU5vPOcKQpgx8LofJK6Jophgj8FlEjFsxJ6dc6jd%2F2bTXdexC1bIFCI3eyiz%2FzLDY73zDRTqqqczFCRMJOOdyI%2FkBfO8l4131ocTGo%2F45Q1M2NAA5EmBQ8L68og3ERdY%2BuFfHEptrueqYQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:23,763 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4263'}
2023-08-03 22:01:23,763 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:23,791 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/config.yaml?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZwCS2fhe%2BxdM23zT84rm8uJMfSS1EBGIe1uWzSj46Va5MuJLh%2BdrCULvHUggHy7QEYFCkLXWtAxIBnFaEccqXDdNpbegIKiLDDqAfNIPW2UuYbQwa15qTxuhII5G1VMz%2F3xllNetvUtkOmSq8JhfDE%2BUXPPaGpVaTn8zPXHFvKN1RAAefNnRoSLWy7%2FV1Uaob5MfPYX%2FjQgy4DO1D6GwqrGxqO%2B7aMyhQlCsKO6NUJfITJOt1wAkbTlG%2FPRgSbbEaG4uK8tgZZsJDnyCboXPOBC5ARaIxkaL2pRdKp0bu4urMkqr9t89AI4gj%2BVsbGKXWBbpGhiR%2FkLS3civssHB%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:23,791 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1206'}
2023-08-03 22:01:23,791 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:24,531 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:24,532 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:25,532 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:25,533 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:26,111 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/requirements.txt?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HIDwxPOA%2Bs9BJuS%2B644bpHIAjHghLwRoRhadGyo5qMgJRh4WiNzpKk7lX3gdhT6oIhncH%2FfcOPoMhjLJF00rdeSmFnSdaiNYi1ZnTeiHwIcsH%2Bd2uptiNOn%2FZ0oOaxWCaf6uK3SihsXZN%2FYHtxhyFhzpnJg7u0K6xtJYBl19T1Yzay%2FP6Tg%2FJz%2FKD9Q0wqnFMsF%2FR%2FceFU5vPOcKQpgx8LofJK6Jophgj8FlEjFsxJ6dc6jd%2F2bTXdexC1bIFCI3eyiz%2FzLDY73zDRTqqqczFCRMJOOdyI%2FkBfO8l4131ocTGo%2F45Q1M2NAA5EmBQ8L68og3ERdY%2BuFfHEptrueqYQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:26,112 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4263'}
2023-08-03 22:01:26,112 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:26,121 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/output.log?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftpQ%2FuUigniI%2F9XD1AMUUMOqpkJ6JLZ4O20G0JRF%2FOwA5IfJzZCyO4%2Fin00RwETvx7aRVgBAs4fSOahG3BK8YZx0G9CkGK3Ta08WjNow1YW%2B1MTJNV5nuV1Chin2yW6H2bRnbLJezUOSR2FpsoIxFXdyjnlF3wYIimFYkOwVQ18KgCQiThtGHV1BFYhbEF2TxZ834nnxA0w6sWP11Ffqz8odGycAWJOnfxCehvqe08JwzLBzs3U%2BQ9ZWIIg6dDR3Ontt7XE2Ezy3Oe4bGsVcnKAT9EQKTHe4aDiVrSnGqquHqQFdM2vIlMpfFFheEh5NYidy%2BRPu23nctMIgaQWd5g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:26,122 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6417'}
2023-08-03 22:01:26,122 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:26,189 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-summary.json?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RI1vMhDYjBNPlY9n58%2BQCMWxXUl0IK8RVtsFsbV3MzTqNiqJZxLblFVkyF92P%2FQe%2BzxgifQsflI66FkOH3Oj78jNES8TV3deCn5tS9VqC4QILwHGCPlLWa%2FrY6N6gyejOt21OdMN8976kzjCSbwIV6H1dus%2FWzYBfEk4m7rvmmMDyW2hfDR59HVDXWybfHkU2Z6psXocnPnoTBp5PsaW32jw4d1I%2BeX0UEZTv9maFX6WRXotLzve1fsaQcIlo9coNgbp%2FTUWhc9pypZI%2F1%2FyXMzTs8adoC9JnwME0q%2BD%2F7LVopEWT57C98RfZRh%2Flaa0bvh9j5pIbe5UDrYT52uoqg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:26,190 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-08-03 22:01:26,190 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:26,375 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/config.yaml?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZwCS2fhe%2BxdM23zT84rm8uJMfSS1EBGIe1uWzSj46Va5MuJLh%2BdrCULvHUggHy7QEYFCkLXWtAxIBnFaEccqXDdNpbegIKiLDDqAfNIPW2UuYbQwa15qTxuhII5G1VMz%2F3xllNetvUtkOmSq8JhfDE%2BUXPPaGpVaTn8zPXHFvKN1RAAefNnRoSLWy7%2FV1Uaob5MfPYX%2FjQgy4DO1D6GwqrGxqO%2B7aMyhQlCsKO6NUJfITJOt1wAkbTlG%2FPRgSbbEaG4uK8tgZZsJDnyCboXPOBC5ARaIxkaL2pRdKp0bu4urMkqr9t89AI4gj%2BVsbGKXWBbpGhiR%2FkLS3civssHB%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:26,375 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1206'}
2023-08-03 22:01:26,375 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:26,533 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:26,534 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:27,535 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:27,535 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:28,535 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:28,536 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:29,537 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: status_report
2023-08-03 22:01:29,537 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:29,538 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:29,957 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-metadata.json?Expires=1691157670&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XWOeT%2BxequiG15fpNbUVz0BXnSnwMf1%2F01RgRLCpVsYhchivkXffpasQ%2B7TyUJIFvU9jHDPs70Nth23guB9iySim5BUpbIrzJWYr7sj83Z9Q5WB8ua%2BfGjj9iUvb0rTkH7mrF90wf%2Fm%2FLIey8fRtY4EsvN5QdjcDq0AEupkWNvJXsz5rLp3%2BtilYrI9G%2FqOXdNXFVss4jWpEQdGc5eq1jR6%2FDJIl84hTYXrLKAb25229M%2BK%2BMmXLGHNQXBqwmUdarEjD4N6%2BH8ataDF10PI%2FMmbbCKiEnOGFAVL00z%2B9654GnL%2BiC8IblD5jXIxWRQRZogqf2W%2BgbSPu2XDkRJMmKw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:29,957 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9248'}
2023-08-03 22:01:29,957 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:30,539 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:30,539 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:30,567 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/requirements.txt?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HIDwxPOA%2Bs9BJuS%2B644bpHIAjHghLwRoRhadGyo5qMgJRh4WiNzpKk7lX3gdhT6oIhncH%2FfcOPoMhjLJF00rdeSmFnSdaiNYi1ZnTeiHwIcsH%2Bd2uptiNOn%2FZ0oOaxWCaf6uK3SihsXZN%2FYHtxhyFhzpnJg7u0K6xtJYBl19T1Yzay%2FP6Tg%2FJz%2FKD9Q0wqnFMsF%2FR%2FceFU5vPOcKQpgx8LofJK6Jophgj8FlEjFsxJ6dc6jd%2F2bTXdexC1bIFCI3eyiz%2FzLDY73zDRTqqqczFCRMJOOdyI%2FkBfO8l4131ocTGo%2F45Q1M2NAA5EmBQ8L68og3ERdY%2BuFfHEptrueqYQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:30,567 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4263'}
2023-08-03 22:01:30,567 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:30,830 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/output.log?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftpQ%2FuUigniI%2F9XD1AMUUMOqpkJ6JLZ4O20G0JRF%2FOwA5IfJzZCyO4%2Fin00RwETvx7aRVgBAs4fSOahG3BK8YZx0G9CkGK3Ta08WjNow1YW%2B1MTJNV5nuV1Chin2yW6H2bRnbLJezUOSR2FpsoIxFXdyjnlF3wYIimFYkOwVQ18KgCQiThtGHV1BFYhbEF2TxZ834nnxA0w6sWP11Ffqz8odGycAWJOnfxCehvqe08JwzLBzs3U%2BQ9ZWIIg6dDR3Ontt7XE2Ezy3Oe4bGsVcnKAT9EQKTHe4aDiVrSnGqquHqQFdM2vIlMpfFFheEh5NYidy%2BRPu23nctMIgaQWd5g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:30,831 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6417'}
2023-08-03 22:01:30,831 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:31,037 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/config.yaml?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZwCS2fhe%2BxdM23zT84rm8uJMfSS1EBGIe1uWzSj46Va5MuJLh%2BdrCULvHUggHy7QEYFCkLXWtAxIBnFaEccqXDdNpbegIKiLDDqAfNIPW2UuYbQwa15qTxuhII5G1VMz%2F3xllNetvUtkOmSq8JhfDE%2BUXPPaGpVaTn8zPXHFvKN1RAAefNnRoSLWy7%2FV1Uaob5MfPYX%2FjQgy4DO1D6GwqrGxqO%2B7aMyhQlCsKO6NUJfITJOt1wAkbTlG%2FPRgSbbEaG4uK8tgZZsJDnyCboXPOBC5ARaIxkaL2pRdKp0bu4urMkqr9t89AI4gj%2BVsbGKXWBbpGhiR%2FkLS3civssHB%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:31,037 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1206'}
2023-08-03 22:01:31,037 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:31,273 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-summary.json?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RI1vMhDYjBNPlY9n58%2BQCMWxXUl0IK8RVtsFsbV3MzTqNiqJZxLblFVkyF92P%2FQe%2BzxgifQsflI66FkOH3Oj78jNES8TV3deCn5tS9VqC4QILwHGCPlLWa%2FrY6N6gyejOt21OdMN8976kzjCSbwIV6H1dus%2FWzYBfEk4m7rvmmMDyW2hfDR59HVDXWybfHkU2Z6psXocnPnoTBp5PsaW32jw4d1I%2BeX0UEZTv9maFX6WRXotLzve1fsaQcIlo9coNgbp%2FTUWhc9pypZI%2F1%2FyXMzTs8adoC9JnwME0q%2BD%2F7LVopEWT57C98RfZRh%2Flaa0bvh9j5pIbe5UDrYT52uoqg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:31,273 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-08-03 22:01:31,273 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:31,539 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:31,539 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:32,540 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:32,541 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:33,541 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:33,542 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:34,542 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:34,543 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: status_report
2023-08-03 22:01:34,543 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:35,543 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:35,544 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:36,544 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:36,545 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:37,546 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:37,546 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:38,546 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:38,547 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:39,547 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: status_report
2023-08-03 22:01:39,548 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:39,548 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:40,043 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/requirements.txt?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HIDwxPOA%2Bs9BJuS%2B644bpHIAjHghLwRoRhadGyo5qMgJRh4WiNzpKk7lX3gdhT6oIhncH%2FfcOPoMhjLJF00rdeSmFnSdaiNYi1ZnTeiHwIcsH%2Bd2uptiNOn%2FZ0oOaxWCaf6uK3SihsXZN%2FYHtxhyFhzpnJg7u0K6xtJYBl19T1Yzay%2FP6Tg%2FJz%2FKD9Q0wqnFMsF%2FR%2FceFU5vPOcKQpgx8LofJK6Jophgj8FlEjFsxJ6dc6jd%2F2bTXdexC1bIFCI3eyiz%2FzLDY73zDRTqqqczFCRMJOOdyI%2FkBfO8l4131ocTGo%2F45Q1M2NAA5EmBQ8L68og3ERdY%2BuFfHEptrueqYQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:40,043 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4263'}
2023-08-03 22:01:40,043 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:40,549 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:40,549 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:40,673 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-summary.json?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RI1vMhDYjBNPlY9n58%2BQCMWxXUl0IK8RVtsFsbV3MzTqNiqJZxLblFVkyF92P%2FQe%2BzxgifQsflI66FkOH3Oj78jNES8TV3deCn5tS9VqC4QILwHGCPlLWa%2FrY6N6gyejOt21OdMN8976kzjCSbwIV6H1dus%2FWzYBfEk4m7rvmmMDyW2hfDR59HVDXWybfHkU2Z6psXocnPnoTBp5PsaW32jw4d1I%2BeX0UEZTv9maFX6WRXotLzve1fsaQcIlo9coNgbp%2FTUWhc9pypZI%2F1%2FyXMzTs8adoC9JnwME0q%2BD%2F7LVopEWT57C98RfZRh%2Flaa0bvh9j5pIbe5UDrYT52uoqg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:40,673 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-08-03 22:01:40,673 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:40,857 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/config.yaml?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZwCS2fhe%2BxdM23zT84rm8uJMfSS1EBGIe1uWzSj46Va5MuJLh%2BdrCULvHUggHy7QEYFCkLXWtAxIBnFaEccqXDdNpbegIKiLDDqAfNIPW2UuYbQwa15qTxuhII5G1VMz%2F3xllNetvUtkOmSq8JhfDE%2BUXPPaGpVaTn8zPXHFvKN1RAAefNnRoSLWy7%2FV1Uaob5MfPYX%2FjQgy4DO1D6GwqrGxqO%2B7aMyhQlCsKO6NUJfITJOt1wAkbTlG%2FPRgSbbEaG4uK8tgZZsJDnyCboXPOBC5ARaIxkaL2pRdKp0bu4urMkqr9t89AI4gj%2BVsbGKXWBbpGhiR%2FkLS3civssHB%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:40,857 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1206'}
2023-08-03 22:01:40,857 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:40,953 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/output.log?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftpQ%2FuUigniI%2F9XD1AMUUMOqpkJ6JLZ4O20G0JRF%2FOwA5IfJzZCyO4%2Fin00RwETvx7aRVgBAs4fSOahG3BK8YZx0G9CkGK3Ta08WjNow1YW%2B1MTJNV5nuV1Chin2yW6H2bRnbLJezUOSR2FpsoIxFXdyjnlF3wYIimFYkOwVQ18KgCQiThtGHV1BFYhbEF2TxZ834nnxA0w6sWP11Ffqz8odGycAWJOnfxCehvqe08JwzLBzs3U%2BQ9ZWIIg6dDR3Ontt7XE2Ezy3Oe4bGsVcnKAT9EQKTHe4aDiVrSnGqquHqQFdM2vIlMpfFFheEh5NYidy%2BRPu23nctMIgaQWd5g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:40,953 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6417'}
2023-08-03 22:01:40,953 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:41,559 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:41,560 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:42,560 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:42,561 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:43,560 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:43,561 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:44,561 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:44,562 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: status_report
2023-08-03 22:01:44,562 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:45,563 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:45,563 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:46,564 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:46,565 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:47,565 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:47,566 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:48,161 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-metadata.json?Expires=1691157670&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XWOeT%2BxequiG15fpNbUVz0BXnSnwMf1%2F01RgRLCpVsYhchivkXffpasQ%2B7TyUJIFvU9jHDPs70Nth23guB9iySim5BUpbIrzJWYr7sj83Z9Q5WB8ua%2BfGjj9iUvb0rTkH7mrF90wf%2Fm%2FLIey8fRtY4EsvN5QdjcDq0AEupkWNvJXsz5rLp3%2BtilYrI9G%2FqOXdNXFVss4jWpEQdGc5eq1jR6%2FDJIl84hTYXrLKAb25229M%2BK%2BMmXLGHNQXBqwmUdarEjD4N6%2BH8ataDF10PI%2FMmbbCKiEnOGFAVL00z%2B9654GnL%2BiC8IblD5jXIxWRQRZogqf2W%2BgbSPu2XDkRJMmKw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:48,161 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9248'}
2023-08-03 22:01:48,161 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:48,566 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:48,567 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:49,567 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: status_report
2023-08-03 22:01:49,568 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:49,569 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:50,569 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:50,570 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:51,570 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:51,571 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:52,571 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:52,571 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:53,572 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:53,572 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:54,573 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:54,573 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: status_report
2023-08-03 22:01:54,574 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:55,574 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:55,575 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:56,574 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:56,575 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:57,119 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-summary.json?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RI1vMhDYjBNPlY9n58%2BQCMWxXUl0IK8RVtsFsbV3MzTqNiqJZxLblFVkyF92P%2FQe%2BzxgifQsflI66FkOH3Oj78jNES8TV3deCn5tS9VqC4QILwHGCPlLWa%2FrY6N6gyejOt21OdMN8976kzjCSbwIV6H1dus%2FWzYBfEk4m7rvmmMDyW2hfDR59HVDXWybfHkU2Z6psXocnPnoTBp5PsaW32jw4d1I%2BeX0UEZTv9maFX6WRXotLzve1fsaQcIlo9coNgbp%2FTUWhc9pypZI%2F1%2FyXMzTs8adoC9JnwME0q%2BD%2F7LVopEWT57C98RfZRh%2Flaa0bvh9j5pIbe5UDrYT52uoqg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:57,119 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-08-03 22:01:57,119 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:57,575 DEBUG   HandlerThread:1453 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-03 22:01:57,576 DEBUG   SenderThread:1453 [sender.py:send_request():402] send_request: poll_exit
2023-08-03 22:01:57,576 WARNING StreamThr :1453 [internal.py:is_dead():414] Internal process exiting, parent pid 1393 disappeared
2023-08-03 22:01:57,576 ERROR   StreamThr :1453 [internal.py:wandb_internal():152] Internal process shutdown.
2023-08-03 22:01:58,116 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/output.log?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftpQ%2FuUigniI%2F9XD1AMUUMOqpkJ6JLZ4O20G0JRF%2FOwA5IfJzZCyO4%2Fin00RwETvx7aRVgBAs4fSOahG3BK8YZx0G9CkGK3Ta08WjNow1YW%2B1MTJNV5nuV1Chin2yW6H2bRnbLJezUOSR2FpsoIxFXdyjnlF3wYIimFYkOwVQ18KgCQiThtGHV1BFYhbEF2TxZ834nnxA0w6sWP11Ffqz8odGycAWJOnfxCehvqe08JwzLBzs3U%2BQ9ZWIIg6dDR3Ontt7XE2Ezy3Oe4bGsVcnKAT9EQKTHe4aDiVrSnGqquHqQFdM2vIlMpfFFheEh5NYidy%2BRPu23nctMIgaQWd5g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:58,116 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6417'}
2023-08-03 22:01:58,116 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:01:58,576 INFO    HandlerThread:1453 [handler.py:finish():845] shutting down handler
2023-08-03 22:01:58,576 INFO    WriterThread:1453 [datastore.py:close():298] close: /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/run-59l06gmp.wandb
2023-08-03 22:01:58,576 INFO    SenderThread:1453 [sender.py:finish():1550] shutting down sender
2023-08-03 22:01:58,576 INFO    SenderThread:1453 [file_pusher.py:finish():168] shutting down file pusher
2023-08-03 22:01:58,577 INFO    SenderThread:1453 [file_pusher.py:join():173] waiting for file pusher
2023-08-03 22:01:59,503 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/requirements.txt?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HIDwxPOA%2Bs9BJuS%2B644bpHIAjHghLwRoRhadGyo5qMgJRh4WiNzpKk7lX3gdhT6oIhncH%2FfcOPoMhjLJF00rdeSmFnSdaiNYi1ZnTeiHwIcsH%2Bd2uptiNOn%2FZ0oOaxWCaf6uK3SihsXZN%2FYHtxhyFhzpnJg7u0K6xtJYBl19T1Yzay%2FP6Tg%2FJz%2FKD9Q0wqnFMsF%2FR%2FceFU5vPOcKQpgx8LofJK6Jophgj8FlEjFsxJ6dc6jd%2F2bTXdexC1bIFCI3eyiz%2FzLDY73zDRTqqqczFCRMJOOdyI%2FkBfO8l4131ocTGo%2F45Q1M2NAA5EmBQ8L68og3ERdY%2BuFfHEptrueqYQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:01:59,503 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4263'}
2023-08-03 22:01:59,503 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:02:00,714 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/config.yaml?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZwCS2fhe%2BxdM23zT84rm8uJMfSS1EBGIe1uWzSj46Va5MuJLh%2BdrCULvHUggHy7QEYFCkLXWtAxIBnFaEccqXDdNpbegIKiLDDqAfNIPW2UuYbQwa15qTxuhII5G1VMz%2F3xllNetvUtkOmSq8JhfDE%2BUXPPaGpVaTn8zPXHFvKN1RAAefNnRoSLWy7%2FV1Uaob5MfPYX%2FjQgy4DO1D6GwqrGxqO%2B7aMyhQlCsKO6NUJfITJOt1wAkbTlG%2FPRgSbbEaG4uK8tgZZsJDnyCboXPOBC5ARaIxkaL2pRdKp0bu4urMkqr9t89AI4gj%2BVsbGKXWBbpGhiR%2FkLS3civssHB%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:02:00,714 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1206'}
2023-08-03 22:02:00,714 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:02:25,022 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-metadata.json?Expires=1691157670&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XWOeT%2BxequiG15fpNbUVz0BXnSnwMf1%2F01RgRLCpVsYhchivkXffpasQ%2B7TyUJIFvU9jHDPs70Nth23guB9iySim5BUpbIrzJWYr7sj83Z9Q5WB8ua%2BfGjj9iUvb0rTkH7mrF90wf%2Fm%2FLIey8fRtY4EsvN5QdjcDq0AEupkWNvJXsz5rLp3%2BtilYrI9G%2FqOXdNXFVss4jWpEQdGc5eq1jR6%2FDJIl84hTYXrLKAb25229M%2BK%2BMmXLGHNQXBqwmUdarEjD4N6%2BH8ataDF10PI%2FMmbbCKiEnOGFAVL00z%2B9654GnL%2BiC8IblD5jXIxWRQRZogqf2W%2BgbSPu2XDkRJMmKw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:02:25,022 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9248'}
2023-08-03 22:02:25,022 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:02:29,836 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-summary.json?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RI1vMhDYjBNPlY9n58%2BQCMWxXUl0IK8RVtsFsbV3MzTqNiqJZxLblFVkyF92P%2FQe%2BzxgifQsflI66FkOH3Oj78jNES8TV3deCn5tS9VqC4QILwHGCPlLWa%2FrY6N6gyejOt21OdMN8976kzjCSbwIV6H1dus%2FWzYBfEk4m7rvmmMDyW2hfDR59HVDXWybfHkU2Z6psXocnPnoTBp5PsaW32jw4d1I%2BeX0UEZTv9maFX6WRXotLzve1fsaQcIlo9coNgbp%2FTUWhc9pypZI%2F1%2FyXMzTs8adoC9JnwME0q%2BD%2F7LVopEWT57C98RfZRh%2Flaa0bvh9j5pIbe5UDrYT52uoqg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:02:29,836 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-08-03 22:02:29,836 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:02:32,971 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/config.yaml?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZwCS2fhe%2BxdM23zT84rm8uJMfSS1EBGIe1uWzSj46Va5MuJLh%2BdrCULvHUggHy7QEYFCkLXWtAxIBnFaEccqXDdNpbegIKiLDDqAfNIPW2UuYbQwa15qTxuhII5G1VMz%2F3xllNetvUtkOmSq8JhfDE%2BUXPPaGpVaTn8zPXHFvKN1RAAefNnRoSLWy7%2FV1Uaob5MfPYX%2FjQgy4DO1D6GwqrGxqO%2B7aMyhQlCsKO6NUJfITJOt1wAkbTlG%2FPRgSbbEaG4uK8tgZZsJDnyCboXPOBC5ARaIxkaL2pRdKp0bu4urMkqr9t89AI4gj%2BVsbGKXWBbpGhiR%2FkLS3civssHB%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:02:32,971 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1206'}
2023-08-03 22:02:32,971 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:02:35,217 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/output.log?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftpQ%2FuUigniI%2F9XD1AMUUMOqpkJ6JLZ4O20G0JRF%2FOwA5IfJzZCyO4%2Fin00RwETvx7aRVgBAs4fSOahG3BK8YZx0G9CkGK3Ta08WjNow1YW%2B1MTJNV5nuV1Chin2yW6H2bRnbLJezUOSR2FpsoIxFXdyjnlF3wYIimFYkOwVQ18KgCQiThtGHV1BFYhbEF2TxZ834nnxA0w6sWP11Ffqz8odGycAWJOnfxCehvqe08JwzLBzs3U%2BQ9ZWIIg6dDR3Ontt7XE2Ezy3Oe4bGsVcnKAT9EQKTHe4aDiVrSnGqquHqQFdM2vIlMpfFFheEh5NYidy%2BRPu23nctMIgaQWd5g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:02:35,217 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6417'}
2023-08-03 22:02:35,217 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:02:35,698 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/requirements.txt?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HIDwxPOA%2Bs9BJuS%2B644bpHIAjHghLwRoRhadGyo5qMgJRh4WiNzpKk7lX3gdhT6oIhncH%2FfcOPoMhjLJF00rdeSmFnSdaiNYi1ZnTeiHwIcsH%2Bd2uptiNOn%2FZ0oOaxWCaf6uK3SihsXZN%2FYHtxhyFhzpnJg7u0K6xtJYBl19T1Yzay%2FP6Tg%2FJz%2FKD9Q0wqnFMsF%2FR%2FceFU5vPOcKQpgx8LofJK6Jophgj8FlEjFsxJ6dc6jd%2F2bTXdexC1bIFCI3eyiz%2FzLDY73zDRTqqqczFCRMJOOdyI%2FkBfO8l4131ocTGo%2F45Q1M2NAA5EmBQ8L68og3ERdY%2BuFfHEptrueqYQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:02:35,698 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4263'}
2023-08-03 22:02:35,698 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:03:37,700 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-metadata.json?Expires=1691157670&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XWOeT%2BxequiG15fpNbUVz0BXnSnwMf1%2F01RgRLCpVsYhchivkXffpasQ%2B7TyUJIFvU9jHDPs70Nth23guB9iySim5BUpbIrzJWYr7sj83Z9Q5WB8ua%2BfGjj9iUvb0rTkH7mrF90wf%2Fm%2FLIey8fRtY4EsvN5QdjcDq0AEupkWNvJXsz5rLp3%2BtilYrI9G%2FqOXdNXFVss4jWpEQdGc5eq1jR6%2FDJIl84hTYXrLKAb25229M%2BK%2BMmXLGHNQXBqwmUdarEjD4N6%2BH8ataDF10PI%2FMmbbCKiEnOGFAVL00z%2B9654GnL%2BiC8IblD5jXIxWRQRZogqf2W%2BgbSPu2XDkRJMmKw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:03:37,700 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9248'}
2023-08-03 22:03:37,700 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:03:40,318 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/output.log?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftpQ%2FuUigniI%2F9XD1AMUUMOqpkJ6JLZ4O20G0JRF%2FOwA5IfJzZCyO4%2Fin00RwETvx7aRVgBAs4fSOahG3BK8YZx0G9CkGK3Ta08WjNow1YW%2B1MTJNV5nuV1Chin2yW6H2bRnbLJezUOSR2FpsoIxFXdyjnlF3wYIimFYkOwVQ18KgCQiThtGHV1BFYhbEF2TxZ834nnxA0w6sWP11Ffqz8odGycAWJOnfxCehvqe08JwzLBzs3U%2BQ9ZWIIg6dDR3Ontt7XE2Ezy3Oe4bGsVcnKAT9EQKTHe4aDiVrSnGqquHqQFdM2vIlMpfFFheEh5NYidy%2BRPu23nctMIgaQWd5g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:03:40,318 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6417'}
2023-08-03 22:03:40,318 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:03:41,196 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-summary.json?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RI1vMhDYjBNPlY9n58%2BQCMWxXUl0IK8RVtsFsbV3MzTqNiqJZxLblFVkyF92P%2FQe%2BzxgifQsflI66FkOH3Oj78jNES8TV3deCn5tS9VqC4QILwHGCPlLWa%2FrY6N6gyejOt21OdMN8976kzjCSbwIV6H1dus%2FWzYBfEk4m7rvmmMDyW2hfDR59HVDXWybfHkU2Z6psXocnPnoTBp5PsaW32jw4d1I%2BeX0UEZTv9maFX6WRXotLzve1fsaQcIlo9coNgbp%2FTUWhc9pypZI%2F1%2FyXMzTs8adoC9JnwME0q%2BD%2F7LVopEWT57C98RfZRh%2Flaa0bvh9j5pIbe5UDrYT52uoqg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:03:41,196 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-08-03 22:03:41,196 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:03:47,139 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/requirements.txt?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HIDwxPOA%2Bs9BJuS%2B644bpHIAjHghLwRoRhadGyo5qMgJRh4WiNzpKk7lX3gdhT6oIhncH%2FfcOPoMhjLJF00rdeSmFnSdaiNYi1ZnTeiHwIcsH%2Bd2uptiNOn%2FZ0oOaxWCaf6uK3SihsXZN%2FYHtxhyFhzpnJg7u0K6xtJYBl19T1Yzay%2FP6Tg%2FJz%2FKD9Q0wqnFMsF%2FR%2FceFU5vPOcKQpgx8LofJK6Jophgj8FlEjFsxJ6dc6jd%2F2bTXdexC1bIFCI3eyiz%2FzLDY73zDRTqqqczFCRMJOOdyI%2FkBfO8l4131ocTGo%2F45Q1M2NAA5EmBQ8L68og3ERdY%2BuFfHEptrueqYQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:03:47,139 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4263'}
2023-08-03 22:03:47,139 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:03:50,514 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/config.yaml?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZwCS2fhe%2BxdM23zT84rm8uJMfSS1EBGIe1uWzSj46Va5MuJLh%2BdrCULvHUggHy7QEYFCkLXWtAxIBnFaEccqXDdNpbegIKiLDDqAfNIPW2UuYbQwa15qTxuhII5G1VMz%2F3xllNetvUtkOmSq8JhfDE%2BUXPPaGpVaTn8zPXHFvKN1RAAefNnRoSLWy7%2FV1Uaob5MfPYX%2FjQgy4DO1D6GwqrGxqO%2B7aMyhQlCsKO6NUJfITJOt1wAkbTlG%2FPRgSbbEaG4uK8tgZZsJDnyCboXPOBC5ARaIxkaL2pRdKp0bu4urMkqr9t89AI4gj%2BVsbGKXWBbpGhiR%2FkLS3civssHB%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:03:50,514 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1206'}
2023-08-03 22:03:50,514 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:05:49,198 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-metadata.json?Expires=1691157670&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XWOeT%2BxequiG15fpNbUVz0BXnSnwMf1%2F01RgRLCpVsYhchivkXffpasQ%2B7TyUJIFvU9jHDPs70Nth23guB9iySim5BUpbIrzJWYr7sj83Z9Q5WB8ua%2BfGjj9iUvb0rTkH7mrF90wf%2Fm%2FLIey8fRtY4EsvN5QdjcDq0AEupkWNvJXsz5rLp3%2BtilYrI9G%2FqOXdNXFVss4jWpEQdGc5eq1jR6%2FDJIl84hTYXrLKAb25229M%2BK%2BMmXLGHNQXBqwmUdarEjD4N6%2BH8ataDF10PI%2FMmbbCKiEnOGFAVL00z%2B9654GnL%2BiC8IblD5jXIxWRQRZogqf2W%2BgbSPu2XDkRJMmKw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:05:49,199 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9248'}
2023-08-03 22:05:49,199 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:06:06,191 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/output.log?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftpQ%2FuUigniI%2F9XD1AMUUMOqpkJ6JLZ4O20G0JRF%2FOwA5IfJzZCyO4%2Fin00RwETvx7aRVgBAs4fSOahG3BK8YZx0G9CkGK3Ta08WjNow1YW%2B1MTJNV5nuV1Chin2yW6H2bRnbLJezUOSR2FpsoIxFXdyjnlF3wYIimFYkOwVQ18KgCQiThtGHV1BFYhbEF2TxZ834nnxA0w6sWP11Ffqz8odGycAWJOnfxCehvqe08JwzLBzs3U%2BQ9ZWIIg6dDR3Ontt7XE2Ezy3Oe4bGsVcnKAT9EQKTHe4aDiVrSnGqquHqQFdM2vIlMpfFFheEh5NYidy%2BRPu23nctMIgaQWd5g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:06:06,191 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6417'}
2023-08-03 22:06:06,191 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:06:13,058 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/config.yaml?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZwCS2fhe%2BxdM23zT84rm8uJMfSS1EBGIe1uWzSj46Va5MuJLh%2BdrCULvHUggHy7QEYFCkLXWtAxIBnFaEccqXDdNpbegIKiLDDqAfNIPW2UuYbQwa15qTxuhII5G1VMz%2F3xllNetvUtkOmSq8JhfDE%2BUXPPaGpVaTn8zPXHFvKN1RAAefNnRoSLWy7%2FV1Uaob5MfPYX%2FjQgy4DO1D6GwqrGxqO%2B7aMyhQlCsKO6NUJfITJOt1wAkbTlG%2FPRgSbbEaG4uK8tgZZsJDnyCboXPOBC5ARaIxkaL2pRdKp0bu4urMkqr9t89AI4gj%2BVsbGKXWBbpGhiR%2FkLS3civssHB%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:06:13,058 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1206'}
2023-08-03 22:06:13,058 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:06:15,011 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-summary.json?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RI1vMhDYjBNPlY9n58%2BQCMWxXUl0IK8RVtsFsbV3MzTqNiqJZxLblFVkyF92P%2FQe%2BzxgifQsflI66FkOH3Oj78jNES8TV3deCn5tS9VqC4QILwHGCPlLWa%2FrY6N6gyejOt21OdMN8976kzjCSbwIV6H1dus%2FWzYBfEk4m7rvmmMDyW2hfDR59HVDXWybfHkU2Z6psXocnPnoTBp5PsaW32jw4d1I%2BeX0UEZTv9maFX6WRXotLzve1fsaQcIlo9coNgbp%2FTUWhc9pypZI%2F1%2FyXMzTs8adoC9JnwME0q%2BD%2F7LVopEWT57C98RfZRh%2Flaa0bvh9j5pIbe5UDrYT52uoqg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:06:15,012 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-08-03 22:06:15,012 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:06:15,489 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/requirements.txt?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HIDwxPOA%2Bs9BJuS%2B644bpHIAjHghLwRoRhadGyo5qMgJRh4WiNzpKk7lX3gdhT6oIhncH%2FfcOPoMhjLJF00rdeSmFnSdaiNYi1ZnTeiHwIcsH%2Bd2uptiNOn%2FZ0oOaxWCaf6uK3SihsXZN%2FYHtxhyFhzpnJg7u0K6xtJYBl19T1Yzay%2FP6Tg%2FJz%2FKD9Q0wqnFMsF%2FR%2FceFU5vPOcKQpgx8LofJK6Jophgj8FlEjFsxJ6dc6jd%2F2bTXdexC1bIFCI3eyiz%2FzLDY73zDRTqqqczFCRMJOOdyI%2FkBfO8l4131ocTGo%2F45Q1M2NAA5EmBQ8L68og3ERdY%2BuFfHEptrueqYQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:06:15,489 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4263'}
2023-08-03 22:06:15,489 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:10:24,911 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/output.log?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftpQ%2FuUigniI%2F9XD1AMUUMOqpkJ6JLZ4O20G0JRF%2FOwA5IfJzZCyO4%2Fin00RwETvx7aRVgBAs4fSOahG3BK8YZx0G9CkGK3Ta08WjNow1YW%2B1MTJNV5nuV1Chin2yW6H2bRnbLJezUOSR2FpsoIxFXdyjnlF3wYIimFYkOwVQ18KgCQiThtGHV1BFYhbEF2TxZ834nnxA0w6sWP11Ffqz8odGycAWJOnfxCehvqe08JwzLBzs3U%2BQ9ZWIIg6dDR3Ontt7XE2Ezy3Oe4bGsVcnKAT9EQKTHe4aDiVrSnGqquHqQFdM2vIlMpfFFheEh5NYidy%2BRPu23nctMIgaQWd5g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:10:24,911 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6417'}
2023-08-03 22:10:24,911 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:10:41,196 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/config.yaml?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZwCS2fhe%2BxdM23zT84rm8uJMfSS1EBGIe1uWzSj46Va5MuJLh%2BdrCULvHUggHy7QEYFCkLXWtAxIBnFaEccqXDdNpbegIKiLDDqAfNIPW2UuYbQwa15qTxuhII5G1VMz%2F3xllNetvUtkOmSq8JhfDE%2BUXPPaGpVaTn8zPXHFvKN1RAAefNnRoSLWy7%2FV1Uaob5MfPYX%2FjQgy4DO1D6GwqrGxqO%2B7aMyhQlCsKO6NUJfITJOt1wAkbTlG%2FPRgSbbEaG4uK8tgZZsJDnyCboXPOBC5ARaIxkaL2pRdKp0bu4urMkqr9t89AI4gj%2BVsbGKXWBbpGhiR%2FkLS3civssHB%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:10:41,197 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1206'}
2023-08-03 22:10:41,197 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:10:49,131 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-summary.json?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RI1vMhDYjBNPlY9n58%2BQCMWxXUl0IK8RVtsFsbV3MzTqNiqJZxLblFVkyF92P%2FQe%2BzxgifQsflI66FkOH3Oj78jNES8TV3deCn5tS9VqC4QILwHGCPlLWa%2FrY6N6gyejOt21OdMN8976kzjCSbwIV6H1dus%2FWzYBfEk4m7rvmmMDyW2hfDR59HVDXWybfHkU2Z6psXocnPnoTBp5PsaW32jw4d1I%2BeX0UEZTv9maFX6WRXotLzve1fsaQcIlo9coNgbp%2FTUWhc9pypZI%2F1%2FyXMzTs8adoC9JnwME0q%2BD%2F7LVopEWT57C98RfZRh%2Flaa0bvh9j5pIbe5UDrYT52uoqg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:10:49,132 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-08-03 22:10:49,132 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:11:05,021 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/requirements.txt?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HIDwxPOA%2Bs9BJuS%2B644bpHIAjHghLwRoRhadGyo5qMgJRh4WiNzpKk7lX3gdhT6oIhncH%2FfcOPoMhjLJF00rdeSmFnSdaiNYi1ZnTeiHwIcsH%2Bd2uptiNOn%2FZ0oOaxWCaf6uK3SihsXZN%2FYHtxhyFhzpnJg7u0K6xtJYBl19T1Yzay%2FP6Tg%2FJz%2FKD9Q0wqnFMsF%2FR%2FceFU5vPOcKQpgx8LofJK6Jophgj8FlEjFsxJ6dc6jd%2F2bTXdexC1bIFCI3eyiz%2FzLDY73zDRTqqqczFCRMJOOdyI%2FkBfO8l4131ocTGo%2F45Q1M2NAA5EmBQ8L68og3ERdY%2BuFfHEptrueqYQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:11:05,021 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4263'}
2023-08-03 22:11:05,021 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:11:06,716 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-metadata.json?Expires=1691157670&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XWOeT%2BxequiG15fpNbUVz0BXnSnwMf1%2F01RgRLCpVsYhchivkXffpasQ%2B7TyUJIFvU9jHDPs70Nth23guB9iySim5BUpbIrzJWYr7sj83Z9Q5WB8ua%2BfGjj9iUvb0rTkH7mrF90wf%2Fm%2FLIey8fRtY4EsvN5QdjcDq0AEupkWNvJXsz5rLp3%2BtilYrI9G%2FqOXdNXFVss4jWpEQdGc5eq1jR6%2FDJIl84hTYXrLKAb25229M%2BK%2BMmXLGHNQXBqwmUdarEjD4N6%2BH8ataDF10PI%2FMmbbCKiEnOGFAVL00z%2B9654GnL%2BiC8IblD5jXIxWRQRZogqf2W%2BgbSPu2XDkRJMmKw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:11:06,716 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9248'}
2023-08-03 22:11:06,716 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:15:45,307 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/output.log?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftpQ%2FuUigniI%2F9XD1AMUUMOqpkJ6JLZ4O20G0JRF%2FOwA5IfJzZCyO4%2Fin00RwETvx7aRVgBAs4fSOahG3BK8YZx0G9CkGK3Ta08WjNow1YW%2B1MTJNV5nuV1Chin2yW6H2bRnbLJezUOSR2FpsoIxFXdyjnlF3wYIimFYkOwVQ18KgCQiThtGHV1BFYhbEF2TxZ834nnxA0w6sWP11Ffqz8odGycAWJOnfxCehvqe08JwzLBzs3U%2BQ9ZWIIg6dDR3Ontt7XE2Ezy3Oe4bGsVcnKAT9EQKTHe4aDiVrSnGqquHqQFdM2vIlMpfFFheEh5NYidy%2BRPu23nctMIgaQWd5g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:15:45,307 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6417'}
2023-08-03 22:15:45,307 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:15:52,338 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/config.yaml?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZwCS2fhe%2BxdM23zT84rm8uJMfSS1EBGIe1uWzSj46Va5MuJLh%2BdrCULvHUggHy7QEYFCkLXWtAxIBnFaEccqXDdNpbegIKiLDDqAfNIPW2UuYbQwa15qTxuhII5G1VMz%2F3xllNetvUtkOmSq8JhfDE%2BUXPPaGpVaTn8zPXHFvKN1RAAefNnRoSLWy7%2FV1Uaob5MfPYX%2FjQgy4DO1D6GwqrGxqO%2B7aMyhQlCsKO6NUJfITJOt1wAkbTlG%2FPRgSbbEaG4uK8tgZZsJDnyCboXPOBC5ARaIxkaL2pRdKp0bu4urMkqr9t89AI4gj%2BVsbGKXWBbpGhiR%2FkLS3civssHB%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:15:52,338 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1206'}
2023-08-03 22:15:52,338 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:16:38,789 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/requirements.txt?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HIDwxPOA%2Bs9BJuS%2B644bpHIAjHghLwRoRhadGyo5qMgJRh4WiNzpKk7lX3gdhT6oIhncH%2FfcOPoMhjLJF00rdeSmFnSdaiNYi1ZnTeiHwIcsH%2Bd2uptiNOn%2FZ0oOaxWCaf6uK3SihsXZN%2FYHtxhyFhzpnJg7u0K6xtJYBl19T1Yzay%2FP6Tg%2FJz%2FKD9Q0wqnFMsF%2FR%2FceFU5vPOcKQpgx8LofJK6Jophgj8FlEjFsxJ6dc6jd%2F2bTXdexC1bIFCI3eyiz%2FzLDY73zDRTqqqczFCRMJOOdyI%2FkBfO8l4131ocTGo%2F45Q1M2NAA5EmBQ8L68og3ERdY%2BuFfHEptrueqYQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:16:38,789 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4263'}
2023-08-03 22:16:38,789 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:16:46,943 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-summary.json?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RI1vMhDYjBNPlY9n58%2BQCMWxXUl0IK8RVtsFsbV3MzTqNiqJZxLblFVkyF92P%2FQe%2BzxgifQsflI66FkOH3Oj78jNES8TV3deCn5tS9VqC4QILwHGCPlLWa%2FrY6N6gyejOt21OdMN8976kzjCSbwIV6H1dus%2FWzYBfEk4m7rvmmMDyW2hfDR59HVDXWybfHkU2Z6psXocnPnoTBp5PsaW32jw4d1I%2BeX0UEZTv9maFX6WRXotLzve1fsaQcIlo9coNgbp%2FTUWhc9pypZI%2F1%2FyXMzTs8adoC9JnwME0q%2BD%2F7LVopEWT57C98RfZRh%2Flaa0bvh9j5pIbe5UDrYT52uoqg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:16:46,943 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-08-03 22:16:46,943 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:17:16,248 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-metadata.json?Expires=1691157670&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XWOeT%2BxequiG15fpNbUVz0BXnSnwMf1%2F01RgRLCpVsYhchivkXffpasQ%2B7TyUJIFvU9jHDPs70Nth23guB9iySim5BUpbIrzJWYr7sj83Z9Q5WB8ua%2BfGjj9iUvb0rTkH7mrF90wf%2Fm%2FLIey8fRtY4EsvN5QdjcDq0AEupkWNvJXsz5rLp3%2BtilYrI9G%2FqOXdNXFVss4jWpEQdGc5eq1jR6%2FDJIl84hTYXrLKAb25229M%2BK%2BMmXLGHNQXBqwmUdarEjD4N6%2BH8ataDF10PI%2FMmbbCKiEnOGFAVL00z%2B9654GnL%2BiC8IblD5jXIxWRQRZogqf2W%2BgbSPu2XDkRJMmKw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:17:16,248 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9248'}
2023-08-03 22:17:16,248 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:21:31,695 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/output.log?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftpQ%2FuUigniI%2F9XD1AMUUMOqpkJ6JLZ4O20G0JRF%2FOwA5IfJzZCyO4%2Fin00RwETvx7aRVgBAs4fSOahG3BK8YZx0G9CkGK3Ta08WjNow1YW%2B1MTJNV5nuV1Chin2yW6H2bRnbLJezUOSR2FpsoIxFXdyjnlF3wYIimFYkOwVQ18KgCQiThtGHV1BFYhbEF2TxZ834nnxA0w6sWP11Ffqz8odGycAWJOnfxCehvqe08JwzLBzs3U%2BQ9ZWIIg6dDR3Ontt7XE2Ezy3Oe4bGsVcnKAT9EQKTHe4aDiVrSnGqquHqQFdM2vIlMpfFFheEh5NYidy%2BRPu23nctMIgaQWd5g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:21:31,696 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6417'}
2023-08-03 22:21:31,696 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:21:38,967 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/config.yaml?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZwCS2fhe%2BxdM23zT84rm8uJMfSS1EBGIe1uWzSj46Va5MuJLh%2BdrCULvHUggHy7QEYFCkLXWtAxIBnFaEccqXDdNpbegIKiLDDqAfNIPW2UuYbQwa15qTxuhII5G1VMz%2F3xllNetvUtkOmSq8JhfDE%2BUXPPaGpVaTn8zPXHFvKN1RAAefNnRoSLWy7%2FV1Uaob5MfPYX%2FjQgy4DO1D6GwqrGxqO%2B7aMyhQlCsKO6NUJfITJOt1wAkbTlG%2FPRgSbbEaG4uK8tgZZsJDnyCboXPOBC5ARaIxkaL2pRdKp0bu4urMkqr9t89AI4gj%2BVsbGKXWBbpGhiR%2FkLS3civssHB%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:21:38,967 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1206'}
2023-08-03 22:21:38,967 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:21:50,212 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/requirements.txt?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HIDwxPOA%2Bs9BJuS%2B644bpHIAjHghLwRoRhadGyo5qMgJRh4WiNzpKk7lX3gdhT6oIhncH%2FfcOPoMhjLJF00rdeSmFnSdaiNYi1ZnTeiHwIcsH%2Bd2uptiNOn%2FZ0oOaxWCaf6uK3SihsXZN%2FYHtxhyFhzpnJg7u0K6xtJYBl19T1Yzay%2FP6Tg%2FJz%2FKD9Q0wqnFMsF%2FR%2FceFU5vPOcKQpgx8LofJK6Jophgj8FlEjFsxJ6dc6jd%2F2bTXdexC1bIFCI3eyiz%2FzLDY73zDRTqqqczFCRMJOOdyI%2FkBfO8l4131ocTGo%2F45Q1M2NAA5EmBQ8L68og3ERdY%2BuFfHEptrueqYQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:21:50,212 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4263'}
2023-08-03 22:21:50,213 ERROR   wandb-upload_3:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:22:59,290 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-summary.json?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RI1vMhDYjBNPlY9n58%2BQCMWxXUl0IK8RVtsFsbV3MzTqNiqJZxLblFVkyF92P%2FQe%2BzxgifQsflI66FkOH3Oj78jNES8TV3deCn5tS9VqC4QILwHGCPlLWa%2FrY6N6gyejOt21OdMN8976kzjCSbwIV6H1dus%2FWzYBfEk4m7rvmmMDyW2hfDR59HVDXWybfHkU2Z6psXocnPnoTBp5PsaW32jw4d1I%2BeX0UEZTv9maFX6WRXotLzve1fsaQcIlo9coNgbp%2FTUWhc9pypZI%2F1%2FyXMzTs8adoC9JnwME0q%2BD%2F7LVopEWT57C98RfZRh%2Flaa0bvh9j5pIbe5UDrYT52uoqg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:22:59,290 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-08-03 22:22:59,290 ERROR   wandb-upload_2:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:23:07,231 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/wandb-metadata.json?Expires=1691157670&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XWOeT%2BxequiG15fpNbUVz0BXnSnwMf1%2F01RgRLCpVsYhchivkXffpasQ%2B7TyUJIFvU9jHDPs70Nth23guB9iySim5BUpbIrzJWYr7sj83Z9Q5WB8ua%2BfGjj9iUvb0rTkH7mrF90wf%2Fm%2FLIey8fRtY4EsvN5QdjcDq0AEupkWNvJXsz5rLp3%2BtilYrI9G%2FqOXdNXFVss4jWpEQdGc5eq1jR6%2FDJIl84hTYXrLKAb25229M%2BK%2BMmXLGHNQXBqwmUdarEjD4N6%2BH8ataDF10PI%2FMmbbCKiEnOGFAVL00z%2B9654GnL%2BiC8IblD5jXIxWRQRZogqf2W%2BgbSPu2XDkRJMmKw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:23:07,231 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9248'}
2023-08-03 22:23:07,231 ERROR   wandb-upload_0:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:27:02,332 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/output.log?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftpQ%2FuUigniI%2F9XD1AMUUMOqpkJ6JLZ4O20G0JRF%2FOwA5IfJzZCyO4%2Fin00RwETvx7aRVgBAs4fSOahG3BK8YZx0G9CkGK3Ta08WjNow1YW%2B1MTJNV5nuV1Chin2yW6H2bRnbLJezUOSR2FpsoIxFXdyjnlF3wYIimFYkOwVQ18KgCQiThtGHV1BFYhbEF2TxZ834nnxA0w6sWP11Ffqz8odGycAWJOnfxCehvqe08JwzLBzs3U%2BQ9ZWIIg6dDR3Ontt7XE2Ezy3Oe4bGsVcnKAT9EQKTHe4aDiVrSnGqquHqQFdM2vIlMpfFFheEh5NYidy%2BRPu23nctMIgaQWd5g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:27:02,332 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6417'}
2023-08-03 22:27:02,332 ERROR   wandb-upload_4:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:27:26,065 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/config.yaml?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZwCS2fhe%2BxdM23zT84rm8uJMfSS1EBGIe1uWzSj46Va5MuJLh%2BdrCULvHUggHy7QEYFCkLXWtAxIBnFaEccqXDdNpbegIKiLDDqAfNIPW2UuYbQwa15qTxuhII5G1VMz%2F3xllNetvUtkOmSq8JhfDE%2BUXPPaGpVaTn8zPXHFvKN1RAAefNnRoSLWy7%2FV1Uaob5MfPYX%2FjQgy4DO1D6GwqrGxqO%2B7aMyhQlCsKO6NUJfITJOt1wAkbTlG%2FPRgSbbEaG4uK8tgZZsJDnyCboXPOBC5ARaIxkaL2pRdKp0bu4urMkqr9t89AI4gj%2BVsbGKXWBbpGhiR%2FkLS3civssHB%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:27:26,066 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1206'}
2023-08-03 22:27:26,066 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2103] upload_file response body: 
2023-08-03 22:27:53,708 INFO    wandb-upload_3:1453 [upload_job.py:push():137] Uploaded file /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/requirements.txt
2023-08-03 22:29:09,231 INFO    wandb-upload_0:1453 [upload_job.py:push():137] Uploaded file /tmp/tmp_4es4ka8wandb/q5ls052s-wandb-metadata.json
2023-08-03 22:29:10,428 INFO    wandb-upload_2:1453 [upload_job.py:push():137] Uploaded file /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/wandb-summary.json
2023-08-03 22:33:06,059 INFO    wandb-upload_4:1453 [upload_job.py:push():137] Uploaded file /root/autodl-tmp/msc_project/wandb/run-20230803_220108-59l06gmp/files/output.log
2023-08-03 22:33:06,163 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ryanzengzh/trl/59l06gmp/config.yaml?Expires=1691157682&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZwCS2fhe%2BxdM23zT84rm8uJMfSS1EBGIe1uWzSj46Va5MuJLh%2BdrCULvHUggHy7QEYFCkLXWtAxIBnFaEccqXDdNpbegIKiLDDqAfNIPW2UuYbQwa15qTxuhII5G1VMz%2F3xllNetvUtkOmSq8JhfDE%2BUXPPaGpVaTn8zPXHFvKN1RAAefNnRoSLWy7%2FV1Uaob5MfPYX%2FjQgy4DO1D6GwqrGxqO%2B7aMyhQlCsKO6NUJfITJOt1wAkbTlG%2FPRgSbbEaG4uK8tgZZsJDnyCboXPOBC5ARaIxkaL2pRdKp0bu4urMkqr9t89AI4gj%2BVsbGKXWBbpGhiR%2FkLS3civssHB%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-08-03 22:33:06,164 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1206'}
2023-08-03 22:33:06,164 ERROR   wandb-upload_1:1453 [internal_api.py:upload_file():2103] upload_file response body: 
